export const checkBoxGroup = [
  {
    value: 'Austria',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Burgenland',
        type: 'child',
        isChecked: false,
        label: 'Burgenland',
      },
      {
        value: 'Carinthia',
        type: 'child',
        isChecked: false,
        label: 'Carinthia',
      },
      {
        value: 'Lower Austria',
        type: 'child',
        isChecked: false,
        label: 'Lower Austria',
      },
      {
        value: 'Upper Austria',
        type: 'child',
        isChecked: false,
        label: 'Upper Austria',
      },
      { value: 'Salzburg', type: 'child', isChecked: false, label: 'Salzburg' },
      { value: 'Styria', type: 'child', isChecked: false, label: 'Styria' },
      { value: 'Tyrol', type: 'child', isChecked: false, label: 'Tyrol' },
      {
        value: 'Vorarlberg',
        type: 'child',
        isChecked: false,
        label: 'Vorarlberg',
      },
      { value: 'Vienna', type: 'child', isChecked: false, label: 'Vienna' },
    ],
    label: 'Austria',
  },

  {
    value: 'Belgium',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Brussels-Capital Region',
        type: 'child',
        isChecked: false,
        label: 'Brussels-Capital Region',
      },
      {
        value: 'Flemish Brabant',
        type: 'child',
        isChecked: false,
        label: 'Flemish Brabant',
      },
      {
        value: 'Walloon Brabant',
        type: 'child',
        isChecked: false,
        label: 'Walloon Brabant',
      },
      { value: 'Antwerp', type: 'child', isChecked: false, label: 'Antwerp' },
      {
        value: 'East Flanders',
        type: 'child',
        isChecked: false,
        label: 'East Flanders',
      },
      {
        value: 'West Flanders',
        type: 'child',
        isChecked: false,
        label: 'West Flanders',
      },
      { value: 'Hainaut', type: 'child', isChecked: false, label: 'Hainaut' },
      { value: 'Liège', type: 'child', isChecked: false, label: 'Liège' },
      { value: 'Limburg', type: 'child', isChecked: false, label: 'Limburg' },
      {
        value: 'Luxembourg',
        type: 'child',
        isChecked: false,
        label: 'Luxembourg',
      },
      { value: 'Namur', type: 'child', isChecked: false, label: 'Namur' },
    ],
    label: 'Belgium',
  },

  {
    value: 'Czech Republic',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Prague', type: 'child', isChecked: false, label: 'Prague' },
      {
        value: 'Central Bohemian',
        type: 'child',
        isChecked: false,
        label: 'Central Bohemian',
      },
      {
        value: 'South Bohemian',
        type: 'child',
        isChecked: false,
        label: 'South Bohemian',
      },
      { value: 'Plzeň', type: 'child', isChecked: false, label: 'Plzeň' },
      {
        value: 'Karlovy Vary',
        type: 'child',
        isChecked: false,
        label: 'Karlovy Vary',
      },
      {
        value: 'Ústí nad Labem',
        type: 'child',
        isChecked: false,
        label: 'Ústí nad Labem',
      },
      { value: 'Liberec', type: 'child', isChecked: false, label: 'Liberec' },
      {
        value: 'Hradec Králové',
        type: 'child',
        isChecked: false,
        label: 'Hradec Králové',
      },
      {
        value: 'Pardubice',
        type: 'child',
        isChecked: false,
        label: 'Pardubice',
      },
      { value: 'Olomouc', type: 'child', isChecked: false, label: 'Olomouc' },
      {
        value: 'Moravian-Silesian',
        type: 'child',
        isChecked: false,
        label: 'Moravian-Silesian',
      },
      {
        value: 'South Moravian',
        type: 'child',
        isChecked: false,
        label: 'South Moravian',
      },
      { value: 'Zlín', type: 'child', isChecked: false, label: 'Zlín' },
      { value: 'Vysočina', type: 'child', isChecked: false, label: 'Vysočina' },
    ],
    label: 'Czech Republic',
  },

  {
    value: 'Denmark',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Capital Region of Denmark',
        type: 'child',
        isChecked: false,
        label: 'Capital Region of Denmark',
      },
      {
        value: 'Central Denmark Region',
        type: 'child',
        isChecked: false,
        label: 'Central Denmark Region',
      },
      {
        value: 'Region of Southern Denmark',
        type: 'child',
        isChecked: false,
        label: 'Region of Southern Denmark',
      },
      {
        value: 'North Denmark Region',
        type: 'child',
        isChecked: false,
        label: 'North Denmark Region',
      },
      {
        value: 'Region of Zealand',
        type: 'child',
        isChecked: false,
        label: 'Region of Zealand',
      },
    ],
    label: 'Denmark',
  },

  {
    value: 'Egypt',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Alexandria',
        type: 'child',
        isChecked: false,
        label: 'Alexandria',
      },
      { value: 'Aswan', type: 'child', isChecked: false, label: 'Aswan' },
      { value: 'Asyut', type: 'child', isChecked: false, label: 'Asyut' },
      { value: 'Beheira', type: 'child', isChecked: false, label: 'Beheira' },
      {
        value: 'Beni Suef',
        type: 'child',
        isChecked: false,
        label: 'Beni Suef',
      },
      { value: 'Cairo', type: 'child', isChecked: false, label: 'Cairo' },
      { value: 'Dakahlia', type: 'child', isChecked: false, label: 'Dakahlia' },
      { value: 'Damietta', type: 'child', isChecked: false, label: 'Damietta' },
      { value: 'Faiyum', type: 'child', isChecked: false, label: 'Faiyum' },
      { value: 'Gharbia', type: 'child', isChecked: false, label: 'Gharbia' },
      { value: 'Giza', type: 'child', isChecked: false, label: 'Giza' },
      { value: 'Ismailia', type: 'child', isChecked: false, label: 'Ismailia' },
      {
        value: 'Kafr El Sheikh',
        type: 'child',
        isChecked: false,
        label: 'Kafr El Sheikh',
      },
      { value: 'Luxor', type: 'child', isChecked: false, label: 'Luxor' },
      { value: 'Matrouh', type: 'child', isChecked: false, label: 'Matrouh' },
      { value: 'Minya', type: 'child', isChecked: false, label: 'Minya' },
      { value: 'Monufia', type: 'child', isChecked: false, label: 'Monufia' },
      {
        value: 'New Valley',
        type: 'child',
        isChecked: false,
        label: 'New Valley',
      },
      {
        value: 'North Sinai',
        type: 'child',
        isChecked: false,
        label: 'North Sinai',
      },
      {
        value: 'Port Said',
        type: 'child',
        isChecked: false,
        label: 'Port Said',
      },
      { value: 'Qalyubia', type: 'child', isChecked: false, label: 'Qalyubia' },
      { value: 'Qena', type: 'child', isChecked: false, label: 'Qena' },
      { value: 'Red Sea', type: 'child', isChecked: false, label: 'Red Sea' },
      { value: 'Sharqia', type: 'child', isChecked: false, label: 'Sharqia' },
      { value: 'Sohag', type: 'child', isChecked: false, label: 'Sohag' },
      {
        value: 'South Sinai',
        type: 'child',
        isChecked: false,
        label: 'South Sinai',
      },
      { value: 'Suez', type: 'child', isChecked: false, label: 'Suez' },
    ],
    label: 'Egypt',
  },

  {
    value: 'Finland',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Åland Islands',
        type: 'child',
        isChecked: false,
        label: 'Åland Islands',
      },
      {
        value: 'Central Finland',
        type: 'child',
        isChecked: false,
        label: 'Central Finland',
      },
      {
        value: 'Central Ostrobothnia',
        type: 'child',
        isChecked: false,
        label: 'Central Ostrobothnia',
      },
      { value: 'Kainuu', type: 'child', isChecked: false, label: 'Kainuu' },
      {
        value: 'Kymenlaakso',
        type: 'child',
        isChecked: false,
        label: 'Kymenlaakso',
      },
      { value: 'Lapland', type: 'child', isChecked: false, label: 'Lapland' },
      {
        value: 'North Karelia',
        type: 'child',
        isChecked: false,
        label: 'North Karelia',
      },
      {
        value: 'Northern Ostrobothnia',
        type: 'child',
        isChecked: false,
        label: 'Northern Ostrobothnia',
      },
      {
        value: 'Northern Savonia',
        type: 'child',
        isChecked: false,
        label: 'Northern Savonia',
      },
      {
        value: 'Ostrobothnia',
        type: 'child',
        isChecked: false,
        label: 'Ostrobothnia',
      },
      {
        value: 'Päijät-Häme',
        type: 'child',
        isChecked: false,
        label: 'Päijät-Häme',
      },
      {
        value: 'Pirkanmaa',
        type: 'child',
        isChecked: false,
        label: 'Pirkanmaa',
      },
      {
        value: 'Satakunta',
        type: 'child',
        isChecked: false,
        label: 'Satakunta',
      },
      {
        value: 'South Karelia',
        type: 'child',
        isChecked: false,
        label: 'South Karelia',
      },
      {
        value: 'Southern Ostrobothnia',
        type: 'child',
        isChecked: false,
        label: 'Southern Ostrobothnia',
      },
      {
        value: 'Southern Savonia',
        type: 'child',
        isChecked: false,
        label: 'Southern Savonia',
      },
      {
        value: 'Southwest Finland',
        type: 'child',
        isChecked: false,
        label: 'Southwest Finland',
      },
      {
        value: 'Tavastia Proper',
        type: 'child',
        isChecked: false,
        label: 'Tavastia Proper',
      },
      { value: 'Uusimaa', type: 'child', isChecked: false, label: 'Uusimaa' },
    ],
    label: 'Finland',
  },

  {
    value: 'France',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Auvergne-Rhône-Alpes',
        type: 'child',
        isChecked: false,
        label: 'Auvergne-Rhône-Alpes',
      },
      {
        value: 'Bourgogne-Franche-Comté',
        type: 'child',
        isChecked: false,
        label: 'Bourgogne-Franche-Comté',
      },
      { value: 'Brittany', type: 'child', isChecked: false, label: 'Brittany' },
      {
        value: 'Centre-Val de Loire',
        type: 'child',
        isChecked: false,
        label: 'Centre-Val de Loire',
      },
      { value: 'Corsica', type: 'child', isChecked: false, label: 'Corsica' },
      {
        value: 'Grand Est',
        type: 'child',
        isChecked: false,
        label: 'Grand Est',
      },
      {
        value: 'Hauts-de-France',
        type: 'child',
        isChecked: false,
        label: 'Hauts-de-France',
      },
      {
        value: 'Île-de-France',
        type: 'child',
        isChecked: false,
        label: 'Île-de-France',
      },
      { value: 'Normandy', type: 'child', isChecked: false, label: 'Normandy' },
      {
        value: 'Nouvelle-Aquitaine',
        type: 'child',
        isChecked: false,
        label: 'Nouvelle-Aquitaine',
      },
      {
        value: 'Occitanie',
        type: 'child',
        isChecked: false,
        label: 'Occitanie',
      },
      {
        value: 'Pays de la Loire',
        type: 'child',
        isChecked: false,
        label: 'Pays de la Loire',
      },
      {
        value: "Provence-Alpes-Côte d'Azur",
        type: 'child',
        isChecked: false,
        label: "Provence-Alpes-Côte d'Azur",
      },
    ],
    label: 'France',
  },

  {
    value: 'Germany',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Baden-Württemberg',
        type: 'child',
        isChecked: false,
        label: 'Baden-Württemberg',
      },
      { value: 'Bavaria', type: 'child', isChecked: false, label: 'Bavaria' },
      { value: 'Berlin', type: 'child', isChecked: false, label: 'Berlin' },
      {
        value: 'Brandenburg',
        type: 'child',
        isChecked: false,
        label: 'Brandenburg',
      },
      { value: 'Bremen', type: 'child', isChecked: false, label: 'Bremen' },
      { value: 'Hamburg', type: 'child', isChecked: false, label: 'Hamburg' },
      { value: 'Hesse', type: 'child', isChecked: false, label: 'Hesse' },
      {
        value: 'Lower Saxony',
        type: 'child',
        isChecked: false,
        label: 'Lower Saxony',
      },
      {
        value: 'Mecklenburg-Vorpommern',
        type: 'child',
        isChecked: false,
        label: 'Mecklenburg-Vorpommern',
      },
      {
        value: 'North Rhine-Westphalia',
        type: 'child',
        isChecked: false,
        label: 'North Rhine-Westphalia',
      },
      {
        value: 'Rhineland-Palatinate',
        type: 'child',
        isChecked: false,
        label: 'Rhineland-Palatinate',
      },
      { value: 'Saarland', type: 'child', isChecked: false, label: 'Saarland' },
      { value: 'Saxony', type: 'child', isChecked: false, label: 'Saxony' },
      {
        value: 'Saxony-Anhalt',
        type: 'child',
        isChecked: false,
        label: 'Saxony-Anhalt',
      },
      {
        value: 'Schleswig-Holstein',
        type: 'child',
        isChecked: false,
        label: 'Schleswig-Holstein',
      },
      {
        value: 'Thuringia',
        type: 'child',
        isChecked: false,
        label: 'Thuringia',
      },
    ],
    label: 'Germany',
  },

  {
    value: 'Greece',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Attica', type: 'child', isChecked: false, label: 'Attica' },
      {
        value: 'Central Greece',
        type: 'child',
        isChecked: false,
        label: 'Central Greece',
      },
      {
        value: 'Central Macedonia',
        type: 'child',
        isChecked: false,
        label: 'Central Macedonia',
      },
      { value: 'Crete', type: 'child', isChecked: false, label: 'Crete' },
      {
        value: 'East Macedonia and Thrace',
        type: 'child',
        isChecked: false,
        label: 'East Macedonia and Thrace',
      },
      { value: 'Epirus', type: 'child', isChecked: false, label: 'Epirus' },
      {
        value: 'Ionian Islands',
        type: 'child',
        isChecked: false,
        label: 'Ionian Islands',
      },
      {
        value: 'North Aegean',
        type: 'child',
        isChecked: false,
        label: 'North Aegean',
      },
      {
        value: 'Peloponnese',
        type: 'child',
        isChecked: false,
        label: 'Peloponnese',
      },
      {
        value: 'South Aegean',
        type: 'child',
        isChecked: false,
        label: 'South Aegean',
      },
      { value: 'Thessaly', type: 'child', isChecked: false, label: 'Thessaly' },
      {
        value: 'West Greece',
        type: 'child',
        isChecked: false,
        label: 'West Greece',
      },
      {
        value: 'West Macedonia',
        type: 'child',
        isChecked: false,
        label: 'West Macedonia',
      },
    ],
    label: 'Greece',
  },

  {
    value: 'Hungary',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Bács-Kiskun',
        type: 'child',
        isChecked: false,
        label: 'Bács-Kiskun',
      },
      { value: 'Baranya', type: 'child', isChecked: false, label: 'Baranya' },
      { value: 'Békés', type: 'child', isChecked: false, label: 'Békés' },
      {
        value: 'Borsod-Abaúj-Zemplén',
        type: 'child',
        isChecked: false,
        label: 'Borsod-Abaúj-Zemplén',
      },
      { value: 'Budapest', type: 'child', isChecked: false, label: 'Budapest' },
      {
        value: 'Csongrád-Csanád',
        type: 'child',
        isChecked: false,
        label: 'Csongrád-Csanád',
      },
      { value: 'Fejér', type: 'child', isChecked: false, label: 'Fejér' },
      {
        value: 'Győr-Moson-Sopron',
        type: 'child',
        isChecked: false,
        label: 'Győr-Moson-Sopron',
      },
      {
        value: 'Hajdú-Bihar',
        type: 'child',
        isChecked: false,
        label: 'Hajdú-Bihar',
      },
      { value: 'Heves', type: 'child', isChecked: false, label: 'Heves' },
      {
        value: 'Jász-Nagykun-Szolnok',
        type: 'child',
        isChecked: false,
        label: 'Jász-Nagykun-Szolnok',
      },
      {
        value: 'Komárom-Esztergom',
        type: 'child',
        isChecked: false,
        label: 'Komárom-Esztergom',
      },
      { value: 'Nógrád', type: 'child', isChecked: false, label: 'Nógrád' },
      { value: 'Pest', type: 'child', isChecked: false, label: 'Pest' },
      { value: 'Somogy', type: 'child', isChecked: false, label: 'Somogy' },
      {
        value: 'Szabolcs-Szatmár-Bereg',
        type: 'child',
        isChecked: false,
        label: 'Szabolcs-Szatmár-Bereg',
      },
      { value: 'Tolna', type: 'child', isChecked: false, label: 'Tolna' },
      { value: 'Vas', type: 'child', isChecked: false, label: 'Vas' },
      { value: 'Veszprém', type: 'child', isChecked: false, label: 'Veszprém' },
      { value: 'Zala', type: 'child', isChecked: false, label: 'Zala' },
    ],
    label: 'Hungary',
  },

  {
    value: 'Indonesia',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Aceh', type: 'child', isChecked: false, label: 'Aceh' },
      { value: 'Bali', type: 'child', isChecked: false, label: 'Bali' },
      { value: 'Banten', type: 'child', isChecked: false, label: 'Banten' },
      { value: 'Bengkulu', type: 'child', isChecked: false, label: 'Bengkulu' },
      {
        value: 'Central Java',
        type: 'child',
        isChecked: false,
        label: 'Central Java',
      },
      {
        value: 'Central Kalimantan',
        type: 'child',
        isChecked: false,
        label: 'Central Kalimantan',
      },
      {
        value: 'Central Sulawesi',
        type: 'child',
        isChecked: false,
        label: 'Central Sulawesi',
      },
      {
        value: 'East Java',
        type: 'child',
        isChecked: false,
        label: 'East Java',
      },
      {
        value: 'East Kalimantan',
        type: 'child',
        isChecked: false,
        label: 'East Kalimantan',
      },
      {
        value: 'East Nusa Tenggara',
        type: 'child',
        isChecked: false,
        label: 'East Nusa Tenggara',
      },
      {
        value: 'Gorontalo',
        type: 'child',
        isChecked: false,
        label: 'Gorontalo',
      },
      {
        value: 'Jakarta Special Capital Region',
        type: 'child',
        isChecked: false,
        label: 'Jakarta Special Capital Region',
      },
      { value: 'Jambi', type: 'child', isChecked: false, label: 'Jambi' },
      { value: 'Lampung', type: 'child', isChecked: false, label: 'Lampung' },
      { value: 'Maluku', type: 'child', isChecked: false, label: 'Maluku' },
      {
        value: 'North Kalimantan',
        type: 'child',
        isChecked: false,
        label: 'North Kalimantan',
      },
      {
        value: 'North Maluku',
        type: 'child',
        isChecked: false,
        label: 'North Maluku',
      },
      {
        value: 'North Sumatra',
        type: 'child',
        isChecked: false,
        label: 'North Sumatra',
      },
      { value: 'Papua', type: 'child', isChecked: false, label: 'Papua' },
      { value: 'Riau', type: 'child', isChecked: false, label: 'Riau' },
      {
        value: 'Riau Islands',
        type: 'child',
        isChecked: false,
        label: 'Riau Islands',
      },
      {
        value: 'South Kalimantan',
        type: 'child',
        isChecked: false,
        label: 'South Kalimantan',
      },
      {
        value: 'South Sulawesi',
        type: 'child',
        isChecked: false,
        label: 'South Sulawesi',
      },
      {
        value: 'South Sumatra',
        type: 'child',
        isChecked: false,
        label: 'South Sumatra',
      },
      {
        value: 'Southeast Sulawesi',
        type: 'child',
        isChecked: false,
        label: 'Southeast Sulawesi',
      },
      {
        value: 'West Java',
        type: 'child',
        isChecked: false,
        label: 'West Java',
      },
      {
        value: 'West Kalimantan',
        type: 'child',
        isChecked: false,
        label: 'West Kalimantan',
      },
      {
        value: 'West Nusa Tenggara',
        type: 'child',
        isChecked: false,
        label: 'West Nusa Tenggara',
      },
      {
        value: 'West Papua',
        type: 'child',
        isChecked: false,
        label: 'West Papua',
      },
      {
        value: 'West Sulawesi',
        type: 'child',
        isChecked: false,
        label: 'West Sulawesi',
      },
      {
        value: 'West Sumatra',
        type: 'child',
        isChecked: false,
        label: 'West Sumatra',
      },
      {
        value: 'Yogyakarta Special Region',
        type: 'child',
        isChecked: false,
        label: 'Yogyakarta Special Region',
      },
    ],
    label: 'Indonesia',
  },

  {
    value: 'Ireland',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Connacht', type: 'child', isChecked: false, label: 'Connacht' },
      { value: 'Leinster', type: 'child', isChecked: false, label: 'Leinster' },
      { value: 'Munster', type: 'child', isChecked: false, label: 'Munster' },
      { value: 'Ulster', type: 'child', isChecked: false, label: 'Ulster' },
    ],
    label: 'Ireland',
  },

  {
    value: 'Italy',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Abruzzo', type: 'child', isChecked: false, label: 'Abruzzo' },
      {
        value: 'Aosta Valley',
        type: 'child',
        isChecked: false,
        label: 'Aosta Valley',
      },
      { value: 'Apulia', type: 'child', isChecked: false, label: 'Apulia' },
      {
        value: 'Basilicata',
        type: 'child',
        isChecked: false,
        label: 'Basilicata',
      },
      { value: 'Calabria', type: 'child', isChecked: false, label: 'Calabria' },
      { value: 'Campania', type: 'child', isChecked: false, label: 'Campania' },
      {
        value: 'Emilia-Romagna',
        type: 'child',
        isChecked: false,
        label: 'Emilia-Romagna',
      },
      {
        value: 'Friuli Venezia Giulia',
        type: 'child',
        isChecked: false,
        label: 'Friuli Venezia Giulia',
      },
      { value: 'Lazio', type: 'child', isChecked: false, label: 'Lazio' },
      { value: 'Liguria', type: 'child', isChecked: false, label: 'Liguria' },
      { value: 'Lombardy', type: 'child', isChecked: false, label: 'Lombardy' },
      { value: 'Marche', type: 'child', isChecked: false, label: 'Marche' },
      { value: 'Molise', type: 'child', isChecked: false, label: 'Molise' },
      { value: 'Piedmont', type: 'child', isChecked: false, label: 'Piedmont' },
      { value: 'Sardinia', type: 'child', isChecked: false, label: 'Sardinia' },
      { value: 'Sicily', type: 'child', isChecked: false, label: 'Sicily' },
      {
        value: 'Trentino-Alto Adige/Südtirol',
        type: 'child',
        isChecked: false,
        label: 'Trentino-Alto Adige/Südtirol',
      },
      { value: 'Tuscany', type: 'child', isChecked: false, label: 'Tuscany' },
      { value: 'Umbria', type: 'child', isChecked: false, label: 'Umbria' },
      { value: 'Veneto', type: 'child', isChecked: false, label: 'Veneto' },
    ],
    label: 'Italy',
  },

  {
    value: 'Kuwait',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Al Ahmadi',
        type: 'child',
        isChecked: false,
        label: 'Al Ahmadi',
      },
      {
        value: 'Al Farwaniyah',
        type: 'child',
        isChecked: false,
        label: 'Al Farwaniyah',
      },
      { value: 'Al Jahra', type: 'child', isChecked: false, label: 'Al Jahra' },
      { value: 'Capital', type: 'child', isChecked: false, label: 'Capital' },
      { value: 'Hawalli', type: 'child', isChecked: false, label: 'Hawalli' },
      {
        value: 'Mubarak Al-Kabeer',
        type: 'child',
        isChecked: false,
        label: 'Mubarak Al-Kabeer',
      },
    ],
    label: 'Kuwait',
  },

  {
    value: 'Malaysia',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Johor', type: 'child', isChecked: false, label: 'Johor' },
      { value: 'Kedah', type: 'child', isChecked: false, label: 'Kedah' },
      { value: 'Kelantan', type: 'child', isChecked: false, label: 'Kelantan' },
      {
        value: 'Kuala Lumpur',
        type: 'child',
        isChecked: false,
        label: 'Kuala Lumpur',
      },
      { value: 'Labuan', type: 'child', isChecked: false, label: 'Labuan' },
      { value: 'Melaka', type: 'child', isChecked: false, label: 'Melaka' },
      {
        value: 'Negeri Sembilan',
        type: 'child',
        isChecked: false,
        label: 'Negeri Sembilan',
      },
      { value: 'Pahang', type: 'child', isChecked: false, label: 'Pahang' },
      { value: 'Penang', type: 'child', isChecked: false, label: 'Penang' },
      { value: 'Perak', type: 'child', isChecked: false, label: 'Perak' },
      { value: 'Perlis', type: 'child', isChecked: false, label: 'Perlis' },
      {
        value: 'Putrajaya',
        type: 'child',
        isChecked: false,
        label: 'Putrajaya',
      },
      { value: 'Sabah', type: 'child', isChecked: false, label: 'Sabah' },
      { value: 'Sarawak', type: 'child', isChecked: false, label: 'Sarawak' },
      { value: 'Selangor', type: 'child', isChecked: false, label: 'Selangor' },
      {
        value: 'Terengganu',
        type: 'child',
        isChecked: false,
        label: 'Terengganu',
      },
    ],
    label: 'Malaysia',
  },

  {
    value: 'Netherlands',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Drenthe', type: 'child', isChecked: false, label: 'Drenthe' },
      {
        value: 'Flevoland',
        type: 'child',
        isChecked: false,
        label: 'Flevoland',
      },
      {
        value: 'Friesland',
        type: 'child',
        isChecked: false,
        label: 'Friesland',
      },
      {
        value: 'Gelderland',
        type: 'child',
        isChecked: false,
        label: 'Gelderland',
      },
      {
        value: 'Groningen',
        type: 'child',
        isChecked: false,
        label: 'Groningen',
      },
      { value: 'Limburg', type: 'child', isChecked: false, label: 'Limburg' },
      {
        value: 'North Brabant',
        type: 'child',
        isChecked: false,
        label: 'North Brabant',
      },
      {
        value: 'North Holland',
        type: 'child',
        isChecked: false,
        label: 'North Holland',
      },
      {
        value: 'Overijssel',
        type: 'child',
        isChecked: false,
        label: 'Overijssel',
      },
      {
        value: 'South Holland',
        type: 'child',
        isChecked: false,
        label: 'South Holland',
      },
      { value: 'Utrecht', type: 'child', isChecked: false, label: 'Utrecht' },
      { value: 'Zeeland', type: 'child', isChecked: false, label: 'Zeeland' },
    ],
    label: 'Netherlands',
  },

  {
    value: 'Norway',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Agder', type: 'child', isChecked: false, label: 'Agder' },
      {
        value: 'Innlandet',
        type: 'child',
        isChecked: false,
        label: 'Innlandet',
      },
      {
        value: 'Møre og Romsdal',
        type: 'child',
        isChecked: false,
        label: 'Møre og Romsdal',
      },
      { value: 'Nordland', type: 'child', isChecked: false, label: 'Nordland' },
      { value: 'Oslo', type: 'child', isChecked: false, label: 'Oslo' },
      { value: 'Rogaland', type: 'child', isChecked: false, label: 'Rogaland' },
      {
        value: 'Troms og Finnmark',
        type: 'child',
        isChecked: false,
        label: 'Troms og Finnmark',
      },
      {
        value: 'Trøndelag',
        type: 'child',
        isChecked: false,
        label: 'Trøndelag',
      },
      {
        value: 'Vestfold og Telemark',
        type: 'child',
        isChecked: false,
        label: 'Vestfold og Telemark',
      },
      { value: 'Vestland', type: 'child', isChecked: false, label: 'Vestland' },
      { value: 'Viken', type: 'child', isChecked: false, label: 'Viken' },
    ],
    label: 'Norway',
  },

  {
    value: 'Poland',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Greater Poland',
        type: 'child',
        isChecked: false,
        label: 'Greater Poland',
      },
      {
        value: 'Kuyavian-Pomeranian',
        type: 'child',
        isChecked: false,
        label: 'Kuyavian-Pomeranian',
      },
      {
        value: 'Lesser Poland',
        type: 'child',
        isChecked: false,
        label: 'Lesser Poland',
      },
      { value: 'Łódź', type: 'child', isChecked: false, label: 'Łódź' },
      {
        value: 'Lower Silesian',
        type: 'child',
        isChecked: false,
        label: 'Lower Silesian',
      },
      { value: 'Lublin', type: 'child', isChecked: false, label: 'Lublin' },
      { value: 'Lubusz', type: 'child', isChecked: false, label: 'Lubusz' },
      { value: 'Masovian', type: 'child', isChecked: false, label: 'Masovian' },
      { value: 'Opole', type: 'child', isChecked: false, label: 'Opole' },
      { value: 'Podlasie', type: 'child', isChecked: false, label: 'Podlasie' },
      {
        value: 'Pomeranian',
        type: 'child',
        isChecked: false,
        label: 'Pomeranian',
      },
      { value: 'Silesian', type: 'child', isChecked: false, label: 'Silesian' },
      {
        value: 'Subcarpathian',
        type: 'child',
        isChecked: false,
        label: 'Subcarpathian',
      },
      {
        value: 'Warmian-Masurian',
        type: 'child',
        isChecked: false,
        label: 'Warmian-Masurian',
      },
      {
        value: 'West Pomeranian',
        type: 'child',
        isChecked: false,
        label: 'West Pomeranian',
      },
    ],
    label: 'Poland',
  },

  {
    value: 'Portugal',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Aveiro', type: 'child', isChecked: false, label: 'Aveiro' },
      { value: 'Azores', type: 'child', isChecked: false, label: 'Azores' },
      { value: 'Beja', type: 'child', isChecked: false, label: 'Beja' },
      { value: 'Braga', type: 'child', isChecked: false, label: 'Braga' },
      { value: 'Bragança', type: 'child', isChecked: false, label: 'Bragança' },
      {
        value: 'Castelo Branco',
        type: 'child',
        isChecked: false,
        label: 'Castelo Branco',
      },
      { value: 'Coimbra', type: 'child', isChecked: false, label: 'Coimbra' },
      { value: 'Évora', type: 'child', isChecked: false, label: 'Évora' },
      { value: 'Faro', type: 'child', isChecked: false, label: 'Faro' },
      { value: 'Guarda', type: 'child', isChecked: false, label: 'Guarda' },
      { value: 'Leiria', type: 'child', isChecked: false, label: 'Leiria' },
      { value: 'Lisbon', type: 'child', isChecked: false, label: 'Lisbon' },
      { value: 'Madeira', type: 'child', isChecked: false, label: 'Madeira' },
      {
        value: 'Portalegre',
        type: 'child',
        isChecked: false,
        label: 'Portalegre',
      },
      { value: 'Porto', type: 'child', isChecked: false, label: 'Porto' },
      { value: 'Santarém', type: 'child', isChecked: false, label: 'Santarém' },
      { value: 'Setúbal', type: 'child', isChecked: false, label: 'Setúbal' },
      {
        value: 'Viana do Castelo',
        type: 'child',
        isChecked: false,
        label: 'Viana do Castelo',
      },
      {
        value: 'Vila Real',
        type: 'child',
        isChecked: false,
        label: 'Vila Real',
      },
      { value: 'Viseu', type: 'child', isChecked: false, label: 'Viseu' },
    ],
    label: 'Portugal',
  },

  {
    value: 'Qatar',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Ad Dawhah',
        type: 'child',
        isChecked: false,
        label: 'Ad Dawhah',
      },
      {
        value: 'Al Daayen',
        type: 'child',
        isChecked: false,
        label: 'Al Daayen',
      },
      { value: 'Al Khor', type: 'child', isChecked: false, label: 'Al Khor' },
      {
        value: 'Al Rayyan',
        type: 'child',
        isChecked: false,
        label: 'Al Rayyan',
      },
      {
        value: 'Al Wakrah',
        type: 'child',
        isChecked: false,
        label: 'Al Wakrah',
      },
      {
        value: 'Al-Shahaniya',
        type: 'child',
        isChecked: false,
        label: 'Al-Shahaniya',
      },
      {
        value: 'Madinat ash Shamal',
        type: 'child',
        isChecked: false,
        label: 'Madinat ash Shamal',
      },
      {
        value: 'Umm Salal',
        type: 'child',
        isChecked: false,
        label: 'Umm Salal',
      },
    ],
    label: 'Qatar',
  },

  {
    value: 'Romania',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Alba', type: 'child', isChecked: false, label: 'Alba' },
      { value: 'Arad', type: 'child', isChecked: false, label: 'Arad' },
      { value: 'Argeș', type: 'child', isChecked: false, label: 'Argeș' },
      { value: 'Bacău', type: 'child', isChecked: false, label: 'Bacău' },
      { value: 'Bihor', type: 'child', isChecked: false, label: 'Bihor' },
      {
        value: 'Bistrița-Năsăud',
        type: 'child',
        isChecked: false,
        label: 'Bistrița-Năsăud',
      },
      { value: 'Botoșani', type: 'child', isChecked: false, label: 'Botoșani' },
      { value: 'Brăila', type: 'child', isChecked: false, label: 'Brăila' },
      { value: 'Brașov', type: 'child', isChecked: false, label: 'Brașov' },
      {
        value: 'Bucharest',
        type: 'child',
        isChecked: false,
        label: 'Bucharest',
      },
      { value: 'Buzău', type: 'child', isChecked: false, label: 'Buzău' },
      { value: 'Călărași', type: 'child', isChecked: false, label: 'Călărași' },
      {
        value: 'Caraș-Severin',
        type: 'child',
        isChecked: false,
        label: 'Caraș-Severin',
      },
      { value: 'Cluj', type: 'child', isChecked: false, label: 'Cluj' },
      {
        value: 'Constanța',
        type: 'child',
        isChecked: false,
        label: 'Constanța',
      },
      { value: 'Covasna', type: 'child', isChecked: false, label: 'Covasna' },
      {
        value: 'Dâmbovița',
        type: 'child',
        isChecked: false,
        label: 'Dâmbovița',
      },
      { value: 'Dolj', type: 'child', isChecked: false, label: 'Dolj' },
      { value: 'Galați', type: 'child', isChecked: false, label: 'Galați' },
      { value: 'Giurgiu', type: 'child', isChecked: false, label: 'Giurgiu' },
      { value: 'Gorj', type: 'child', isChecked: false, label: 'Gorj' },
      { value: 'Harghita', type: 'child', isChecked: false, label: 'Harghita' },
      {
        value: 'Hunedoara',
        type: 'child',
        isChecked: false,
        label: 'Hunedoara',
      },
      { value: 'Ialomița', type: 'child', isChecked: false, label: 'Ialomița' },
      { value: 'Iași', type: 'child', isChecked: false, label: 'Iași' },
      { value: 'Ilfov', type: 'child', isChecked: false, label: 'Ilfov' },
      {
        value: 'Maramureș',
        type: 'child',
        isChecked: false,
        label: 'Maramureș',
      },
      {
        value: 'Mehedinți',
        type: 'child',
        isChecked: false,
        label: 'Mehedinți',
      },
      { value: 'Mureș', type: 'child', isChecked: false, label: 'Mureș' },
      { value: 'Neamț', type: 'child', isChecked: false, label: 'Neamț' },
      { value: 'Olt', type: 'child', isChecked: false, label: 'Olt' },
      { value: 'Prahova', type: 'child', isChecked: false, label: 'Prahova' },
      { value: 'Sălaj', type: 'child', isChecked: false, label: 'Sălaj' },
      {
        value: 'Satu Mare',
        type: 'child',
        isChecked: false,
        label: 'Satu Mare',
      },
      { value: 'Sibiu', type: 'child', isChecked: false, label: 'Sibiu' },
      { value: 'Suceava', type: 'child', isChecked: false, label: 'Suceava' },
      {
        value: 'Teleorman',
        type: 'child',
        isChecked: false,
        label: 'Teleorman',
      },
      { value: 'Timiș', type: 'child', isChecked: false, label: 'Timiș' },
      { value: 'Tulcea', type: 'child', isChecked: false, label: 'Tulcea' },
      { value: 'Vâlcea', type: 'child', isChecked: false, label: 'Vâlcea' },
      { value: 'Vaslui', type: 'child', isChecked: false, label: 'Vaslui' },
      { value: 'Vrancea', type: 'child', isChecked: false, label: 'Vrancea' },
    ],
    label: 'Romania',
  },

  {
    value: 'Saudi Arabia',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Al Bahah', type: 'child', isChecked: false, label: 'Al Bahah' },
      { value: 'Al Jawf', type: 'child', isChecked: false, label: 'Al Jawf' },
      {
        value: 'Al Madinah',
        type: 'child',
        isChecked: false,
        label: 'Al Madinah',
      },
      {
        value: 'Al-Qassim',
        type: 'child',
        isChecked: false,
        label: 'Al-Qassim',
      },
      { value: "'Asir", type: 'child', isChecked: false, label: "'Asir" },
      {
        value: 'Eastern Province',
        type: 'child',
        isChecked: false,
        label: 'Eastern Province',
      },
      { value: "Ha'il", type: 'child', isChecked: false, label: "Ha'il" },
      { value: 'Jazan', type: 'child', isChecked: false, label: 'Jazan' },
      { value: 'Makkah', type: 'child', isChecked: false, label: 'Makkah' },
      { value: 'Najran', type: 'child', isChecked: false, label: 'Najran' },
      {
        value: 'Northern Borders',
        type: 'child',
        isChecked: false,
        label: 'Northern Borders',
      },
      { value: 'Riyadh', type: 'child', isChecked: false, label: 'Riyadh' },
      { value: 'Tabuk', type: 'child', isChecked: false, label: 'Tabuk' },
    ],
    label: 'Saudi Arabia',
  },

  {
    value: 'South Korea',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Busan', type: 'child', isChecked: false, label: 'Busan' },
      {
        value: 'Chungcheongbuk-do',
        type: 'child',
        isChecked: false,
        label: 'Chungcheongbuk-do',
      },
      {
        value: 'Chungcheongnam-do',
        type: 'child',
        isChecked: false,
        label: 'Chungcheongnam-do',
      },
      { value: 'Daegu', type: 'child', isChecked: false, label: 'Daegu' },
      { value: 'Daejeon', type: 'child', isChecked: false, label: 'Daejeon' },
      {
        value: 'Gangwon-do',
        type: 'child',
        isChecked: false,
        label: 'Gangwon-do',
      },
      { value: 'Gwangju', type: 'child', isChecked: false, label: 'Gwangju' },
      {
        value: 'Gyeonggi-do',
        type: 'child',
        isChecked: false,
        label: 'Gyeonggi-do',
      },
      {
        value: 'Gyeongsangbuk-do',
        type: 'child',
        isChecked: false,
        label: 'Gyeongsangbuk-do',
      },
      {
        value: 'Gyeongsangnam-do',
        type: 'child',
        isChecked: false,
        label: 'Gyeongsangnam-do',
      },
      { value: 'Incheon', type: 'child', isChecked: false, label: 'Incheon' },
      { value: 'Jeju', type: 'child', isChecked: false, label: 'Jeju' },
      {
        value: 'Jeollabuk-do',
        type: 'child',
        isChecked: false,
        label: 'Jeollabuk-do',
      },
      {
        value: 'Jeollanam-do',
        type: 'child',
        isChecked: false,
        label: 'Jeollanam-do',
      },
      { value: 'Sejong', type: 'child', isChecked: false, label: 'Sejong' },
      { value: 'Seoul', type: 'child', isChecked: false, label: 'Seoul' },
      { value: 'Ulsan', type: 'child', isChecked: false, label: 'Ulsan' },
    ],
    label: 'South Korea',
  },

  {
    value: 'Spain',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Andalusia',
        type: 'child',
        isChecked: false,
        label: 'Andalusia',
      },
      { value: 'Aragon', type: 'child', isChecked: false, label: 'Aragon' },
      { value: 'Asturias', type: 'child', isChecked: false, label: 'Asturias' },
      {
        value: 'Balearic Islands',
        type: 'child',
        isChecked: false,
        label: 'Balearic Islands',
      },
      {
        value: 'Basque Country',
        type: 'child',
        isChecked: false,
        label: 'Basque Country',
      },
      {
        value: 'Canary Islands',
        type: 'child',
        isChecked: false,
        label: 'Canary Islands',
      },
      {
        value: 'Cantabria',
        type: 'child',
        isChecked: false,
        label: 'Cantabria',
      },
      {
        value: 'Castile and León',
        type: 'child',
        isChecked: false,
        label: 'Castile and León',
      },
      {
        value: 'Castilla-La Mancha',
        type: 'child',
        isChecked: false,
        label: 'Castilla-La Mancha',
      },
      {
        value: 'Catalonia',
        type: 'child',
        isChecked: false,
        label: 'Catalonia',
      },
      {
        value: 'Extremadura',
        type: 'child',
        isChecked: false,
        label: 'Extremadura',
      },
      { value: 'Galicia', type: 'child', isChecked: false, label: 'Galicia' },
      { value: 'La Rioja', type: 'child', isChecked: false, label: 'La Rioja' },
      { value: 'Madrid', type: 'child', isChecked: false, label: 'Madrid' },
      { value: 'Murcia', type: 'child', isChecked: false, label: 'Murcia' },
      { value: 'Navarre', type: 'child', isChecked: false, label: 'Navarre' },
      {
        value: 'Valencian Community',
        type: 'child',
        isChecked: false,
        label: 'Valencian Community',
      },
    ],
    label: 'Spain',
  },

  {
    value: 'Sweden',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Blekinge', type: 'child', isChecked: false, label: 'Blekinge' },
      { value: 'Dalarna', type: 'child', isChecked: false, label: 'Dalarna' },
      { value: 'Gotland', type: 'child', isChecked: false, label: 'Gotland' },
      {
        value: 'Gävleborg',
        type: 'child',
        isChecked: false,
        label: 'Gävleborg',
      },
      { value: 'Halland', type: 'child', isChecked: false, label: 'Halland' },
      { value: 'Jämtland', type: 'child', isChecked: false, label: 'Jämtland' },
      {
        value: 'Jönköping',
        type: 'child',
        isChecked: false,
        label: 'Jönköping',
      },
      { value: 'Kalmar', type: 'child', isChecked: false, label: 'Kalmar' },
      {
        value: 'Kronoberg',
        type: 'child',
        isChecked: false,
        label: 'Kronoberg',
      },
      {
        value: 'Norrbotten',
        type: 'child',
        isChecked: false,
        label: 'Norrbotten',
      },
      { value: 'Örebro', type: 'child', isChecked: false, label: 'Örebro' },
      {
        value: 'Östergötland',
        type: 'child',
        isChecked: false,
        label: 'Östergötland',
      },
      { value: 'Skåne', type: 'child', isChecked: false, label: 'Skåne' },
      {
        value: 'Stockholm',
        type: 'child',
        isChecked: false,
        label: 'Stockholm',
      },
      {
        value: 'Södermanland',
        type: 'child',
        isChecked: false,
        label: 'Södermanland',
      },
      { value: 'Uppsala', type: 'child', isChecked: false, label: 'Uppsala' },
      { value: 'Värmland', type: 'child', isChecked: false, label: 'Värmland' },
      {
        value: 'Västerbotten',
        type: 'child',
        isChecked: false,
        label: 'Västerbotten',
      },
      {
        value: 'Västernorrland',
        type: 'child',
        isChecked: false,
        label: 'Västernorrland',
      },
      {
        value: 'Västmanland',
        type: 'child',
        isChecked: false,
        label: 'Västmanland',
      },
      {
        value: 'Västra Götaland',
        type: 'child',
        isChecked: false,
        label: 'Västra Götaland',
      },
    ],
    label: 'Sweden',
  },

  {
    value: 'Switzerland',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Aargau', type: 'child', isChecked: false, label: 'Aargau' },
      {
        value: 'Appenzell Ausserrhoden',
        type: 'child',
        isChecked: false,
        label: 'Appenzell Ausserrhoden',
      },
      {
        value: 'Appenzell Innerrhoden',
        type: 'child',
        isChecked: false,
        label: 'Appenzell Innerrhoden',
      },
      {
        value: 'Basel-Landschaft',
        type: 'child',
        isChecked: false,
        label: 'Basel-Landschaft',
      },
      {
        value: 'Basel-Stadt',
        type: 'child',
        isChecked: false,
        label: 'Basel-Stadt',
      },
      { value: 'Bern', type: 'child', isChecked: false, label: 'Bern' },
      { value: 'Fribourg', type: 'child', isChecked: false, label: 'Fribourg' },
      { value: 'Geneva', type: 'child', isChecked: false, label: 'Geneva' },
      { value: 'Glarus', type: 'child', isChecked: false, label: 'Glarus' },
      {
        value: 'Graubünden',
        type: 'child',
        isChecked: false,
        label: 'Graubünden',
      },
      { value: 'Jura', type: 'child', isChecked: false, label: 'Jura' },
      { value: 'Lucerne', type: 'child', isChecked: false, label: 'Lucerne' },
      {
        value: 'Neuchâtel',
        type: 'child',
        isChecked: false,
        label: 'Neuchâtel',
      },
      {
        value: 'Nidwalden',
        type: 'child',
        isChecked: false,
        label: 'Nidwalden',
      },
      { value: 'Obwalden', type: 'child', isChecked: false, label: 'Obwalden' },
      {
        value: 'Schaffhausen',
        type: 'child',
        isChecked: false,
        label: 'Schaffhausen',
      },
      { value: 'Schwyz', type: 'child', isChecked: false, label: 'Schwyz' },
      {
        value: 'Solothurn',
        type: 'child',
        isChecked: false,
        label: 'Solothurn',
      },
      {
        value: 'St. Gallen',
        type: 'child',
        isChecked: false,
        label: 'St. Gallen',
      },
      { value: 'Thurgau', type: 'child', isChecked: false, label: 'Thurgau' },
      { value: 'Ticino', type: 'child', isChecked: false, label: 'Ticino' },
      { value: 'Uri', type: 'child', isChecked: false, label: 'Uri' },
      { value: 'Valais', type: 'child', isChecked: false, label: 'Valais' },
      { value: 'Vaud', type: 'child', isChecked: false, label: 'Vaud' },
      { value: 'Zug', type: 'child', isChecked: false, label: 'Zug' },
      { value: 'Zurich', type: 'child', isChecked: false, label: 'Zurich' },
    ],
    label: 'Switzerland',
  },

  {
    value: 'Thailand',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Amnat Charoen',
        type: 'child',
        isChecked: false,
        label: 'Amnat Charoen',
      },
      {
        value: 'Ang Thong',
        type: 'child',
        isChecked: false,
        label: 'Ang Thong',
      },
      { value: 'Bangkok', type: 'child', isChecked: false, label: 'Bangkok' },
      {
        value: 'Bueng Kan',
        type: 'child',
        isChecked: false,
        label: 'Bueng Kan',
      },
      { value: 'Buri Ram', type: 'child', isChecked: false, label: 'Buri Ram' },
      {
        value: 'Chachoengsao',
        type: 'child',
        isChecked: false,
        label: 'Chachoengsao',
      },
      { value: 'Chai Nat', type: 'child', isChecked: false, label: 'Chai Nat' },
      {
        value: 'Chaiyaphum',
        type: 'child',
        isChecked: false,
        label: 'Chaiyaphum',
      },
      {
        value: 'Chanthaburi',
        type: 'child',
        isChecked: false,
        label: 'Chanthaburi',
      },
      {
        value: 'Chiang Mai',
        type: 'child',
        isChecked: false,
        label: 'Chiang Mai',
      },
      {
        value: 'Chiang Rai',
        type: 'child',
        isChecked: false,
        label: 'Chiang Rai',
      },
      { value: 'Chonburi', type: 'child', isChecked: false, label: 'Chonburi' },
      { value: 'Chumphon', type: 'child', isChecked: false, label: 'Chumphon' },
      { value: 'Kalasin', type: 'child', isChecked: false, label: 'Kalasin' },
      {
        value: 'Kamphaeng Phet',
        type: 'child',
        isChecked: false,
        label: 'Kamphaeng Phet',
      },
      {
        value: 'Kanchanaburi',
        type: 'child',
        isChecked: false,
        label: 'Kanchanaburi',
      },
      {
        value: 'Khon Kaen',
        type: 'child',
        isChecked: false,
        label: 'Khon Kaen',
      },
      { value: 'Krabi', type: 'child', isChecked: false, label: 'Krabi' },
      { value: 'Lampang', type: 'child', isChecked: false, label: 'Lampang' },
      { value: 'Lamphun', type: 'child', isChecked: false, label: 'Lamphun' },
      { value: 'Loei', type: 'child', isChecked: false, label: 'Loei' },
      { value: 'Lopburi', type: 'child', isChecked: false, label: 'Lopburi' },
      {
        value: 'Mae Hong Son',
        type: 'child',
        isChecked: false,
        label: 'Mae Hong Son',
      },
      {
        value: 'Maha Sarakham',
        type: 'child',
        isChecked: false,
        label: 'Maha Sarakham',
      },
      { value: 'Mukdahan', type: 'child', isChecked: false, label: 'Mukdahan' },
      {
        value: 'Nakhon Nayok',
        type: 'child',
        isChecked: false,
        label: 'Nakhon Nayok',
      },
      {
        value: 'Nakhon Pathom',
        type: 'child',
        isChecked: false,
        label: 'Nakhon Pathom',
      },
      {
        value: 'Nakhon Phanom',
        type: 'child',
        isChecked: false,
        label: 'Nakhon Phanom',
      },
      {
        value: 'Nakhon Ratchasima',
        type: 'child',
        isChecked: false,
        label: 'Nakhon Ratchasima',
      },
      {
        value: 'Nakhon Sawan',
        type: 'child',
        isChecked: false,
        label: 'Nakhon Sawan',
      },
      {
        value: 'Nakhon Si Thammarat',
        type: 'child',
        isChecked: false,
        label: 'Nakhon Si Thammarat',
      },
      { value: 'Nan', type: 'child', isChecked: false, label: 'Nan' },
      {
        value: 'Narathiwat',
        type: 'child',
        isChecked: false,
        label: 'Narathiwat',
      },
      {
        value: 'Nong Bua Lam Phu',
        type: 'child',
        isChecked: false,
        label: 'Nong Bua Lam Phu',
      },
      {
        value: 'Nong Khai',
        type: 'child',
        isChecked: false,
        label: 'Nong Khai',
      },
      {
        value: 'Nonthaburi',
        type: 'child',
        isChecked: false,
        label: 'Nonthaburi',
      },
      {
        value: 'Pathum Thani',
        type: 'child',
        isChecked: false,
        label: 'Pathum Thani',
      },
      { value: 'Pattani', type: 'child', isChecked: false, label: 'Pattani' },
      { value: 'Phangnga', type: 'child', isChecked: false, label: 'Phangnga' },
      {
        value: 'Phatthalung',
        type: 'child',
        isChecked: false,
        label: 'Phatthalung',
      },
      { value: 'Phayao', type: 'child', isChecked: false, label: 'Phayao' },
      {
        value: 'Phetchabun',
        type: 'child',
        isChecked: false,
        label: 'Phetchabun',
      },
      {
        value: 'Phetchaburi',
        type: 'child',
        isChecked: false,
        label: 'Phetchaburi',
      },
      { value: 'Phichit', type: 'child', isChecked: false, label: 'Phichit' },
      {
        value: 'Phitsanulok',
        type: 'child',
        isChecked: false,
        label: 'Phitsanulok',
      },
      {
        value: 'Phra Nakhon Si Ayutthaya',
        type: 'child',
        isChecked: false,
        label: 'Phra Nakhon Si Ayutthaya',
      },
      { value: 'Phrae', type: 'child', isChecked: false, label: 'Phrae' },
      { value: 'Phuket', type: 'child', isChecked: false, label: 'Phuket' },
      {
        value: 'Prachinburi',
        type: 'child',
        isChecked: false,
        label: 'Prachinburi',
      },
      {
        value: 'Prachuap Khiri Khan',
        type: 'child',
        isChecked: false,
        label: 'Prachuap Khiri Khan',
      },
      { value: 'Ranong', type: 'child', isChecked: false, label: 'Ranong' },
      {
        value: 'Ratchaburi',
        type: 'child',
        isChecked: false,
        label: 'Ratchaburi',
      },
      { value: 'Rayong', type: 'child', isChecked: false, label: 'Rayong' },
      { value: 'Roi Et', type: 'child', isChecked: false, label: 'Roi Et' },
      { value: 'Sa Kaeo', type: 'child', isChecked: false, label: 'Sa Kaeo' },
      {
        value: 'Sakon Nakhon',
        type: 'child',
        isChecked: false,
        label: 'Sakon Nakhon',
      },
      {
        value: 'Samut Prakan',
        type: 'child',
        isChecked: false,
        label: 'Samut Prakan',
      },
      {
        value: 'Samut Sakhon',
        type: 'child',
        isChecked: false,
        label: 'Samut Sakhon',
      },
      {
        value: 'Samut Songkhram',
        type: 'child',
        isChecked: false,
        label: 'Samut Songkhram',
      },
      { value: 'Saraburi', type: 'child', isChecked: false, label: 'Saraburi' },
      { value: 'Satun', type: 'child', isChecked: false, label: 'Satun' },
      {
        value: 'Sing Buri',
        type: 'child',
        isChecked: false,
        label: 'Sing Buri',
      },
      { value: 'Sisaket', type: 'child', isChecked: false, label: 'Sisaket' },
      { value: 'Songkhla', type: 'child', isChecked: false, label: 'Songkhla' },
      {
        value: 'Sukhothai',
        type: 'child',
        isChecked: false,
        label: 'Sukhothai',
      },
      {
        value: 'Suphan Buri',
        type: 'child',
        isChecked: false,
        label: 'Suphan Buri',
      },
      {
        value: 'Surat Thani',
        type: 'child',
        isChecked: false,
        label: 'Surat Thani',
      },
      { value: 'Surin', type: 'child', isChecked: false, label: 'Surin' },
      { value: 'Tak', type: 'child', isChecked: false, label: 'Tak' },
      { value: 'Trang', type: 'child', isChecked: false, label: 'Trang' },
      { value: 'Trat', type: 'child', isChecked: false, label: 'Trat' },
      {
        value: 'Ubon Ratchathani',
        type: 'child',
        isChecked: false,
        label: 'Ubon Ratchathani',
      },
      {
        value: 'Udon Thani',
        type: 'child',
        isChecked: false,
        label: 'Udon Thani',
      },
      {
        value: 'Uthai Thani',
        type: 'child',
        isChecked: false,
        label: 'Uthai Thani',
      },
      {
        value: 'Uttaradit',
        type: 'child',
        isChecked: false,
        label: 'Uttaradit',
      },
      { value: 'Yala', type: 'child', isChecked: false, label: 'Yala' },
      { value: 'Yasothon', type: 'child', isChecked: false, label: 'Yasothon' },
    ],
    label: 'Thailand',
  },

  {
    value: 'Turkey',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Adana', type: 'child', isChecked: false, label: 'Adana' },
      { value: 'Adıyaman', type: 'child', isChecked: false, label: 'Adıyaman' },
      {
        value: 'Afyonkarahisar',
        type: 'child',
        isChecked: false,
        label: 'Afyonkarahisar',
      },
      { value: 'Ağrı', type: 'child', isChecked: false, label: 'Ağrı' },
      { value: 'Aksaray', type: 'child', isChecked: false, label: 'Aksaray' },
      { value: 'Amasya', type: 'child', isChecked: false, label: 'Amasya' },
      { value: 'Ankara', type: 'child', isChecked: false, label: 'Ankara' },
      { value: 'Antalya', type: 'child', isChecked: false, label: 'Antalya' },
      { value: 'Ardahan', type: 'child', isChecked: false, label: 'Ardahan' },
      { value: 'Artvin', type: 'child', isChecked: false, label: 'Artvin' },
      { value: 'Aydın', type: 'child', isChecked: false, label: 'Aydın' },
      {
        value: 'Balıkesir',
        type: 'child',
        isChecked: false,
        label: 'Balıkesir',
      },
      { value: 'Bartın', type: 'child', isChecked: false, label: 'Bartın' },
      { value: 'Batman', type: 'child', isChecked: false, label: 'Batman' },
      { value: 'Bayburt', type: 'child', isChecked: false, label: 'Bayburt' },
      { value: 'Bilecik', type: 'child', isChecked: false, label: 'Bilecik' },
      { value: 'Bingöl', type: 'child', isChecked: false, label: 'Bingöl' },
      { value: 'Bitlis', type: 'child', isChecked: false, label: 'Bitlis' },
      { value: 'Bolu', type: 'child', isChecked: false, label: 'Bolu' },
      { value: 'Burdur', type: 'child', isChecked: false, label: 'Burdur' },
      { value: 'Bursa', type: 'child', isChecked: false, label: 'Bursa' },
      {
        value: 'Çanakkale',
        type: 'child',
        isChecked: false,
        label: 'Çanakkale',
      },
      { value: 'Çankırı', type: 'child', isChecked: false, label: 'Çankırı' },
      { value: 'Çorum', type: 'child', isChecked: false, label: 'Çorum' },
      { value: 'Denizli', type: 'child', isChecked: false, label: 'Denizli' },
      {
        value: 'Diyarbakır',
        type: 'child',
        isChecked: false,
        label: 'Diyarbakır',
      },
      { value: 'Düzce', type: 'child', isChecked: false, label: 'Düzce' },
      { value: 'Edirne', type: 'child', isChecked: false, label: 'Edirne' },
      { value: 'Elazığ', type: 'child', isChecked: false, label: 'Elazığ' },
      { value: 'Erzincan', type: 'child', isChecked: false, label: 'Erzincan' },
      { value: 'Erzurum', type: 'child', isChecked: false, label: 'Erzurum' },
      {
        value: 'Eskişehir',
        type: 'child',
        isChecked: false,
        label: 'Eskişehir',
      },
      {
        value: 'Gaziantep',
        type: 'child',
        isChecked: false,
        label: 'Gaziantep',
      },
      { value: 'Giresun', type: 'child', isChecked: false, label: 'Giresun' },
      {
        value: 'Gümüşhane',
        type: 'child',
        isChecked: false,
        label: 'Gümüşhane',
      },
      { value: 'Hakkari', type: 'child', isChecked: false, label: 'Hakkari' },
      { value: 'Hatay', type: 'child', isChecked: false, label: 'Hatay' },
      { value: 'Iğdır', type: 'child', isChecked: false, label: 'Iğdır' },
      { value: 'Isparta', type: 'child', isChecked: false, label: 'Isparta' },
      { value: 'Istanbul', type: 'child', isChecked: false, label: 'Istanbul' },
      { value: 'İzmir', type: 'child', isChecked: false, label: 'İzmir' },
      {
        value: 'Kahramanmaraş',
        type: 'child',
        isChecked: false,
        label: 'Kahramanmaraş',
      },
      { value: 'Karabük', type: 'child', isChecked: false, label: 'Karabük' },
      { value: 'Karaman', type: 'child', isChecked: false, label: 'Karaman' },
      { value: 'Kars', type: 'child', isChecked: false, label: 'Kars' },
      {
        value: 'Kastamonu',
        type: 'child',
        isChecked: false,
        label: 'Kastamonu',
      },
      { value: 'Kayseri', type: 'child', isChecked: false, label: 'Kayseri' },
      { value: 'Kilis', type: 'child', isChecked: false, label: 'Kilis' },
      {
        value: 'Kırıkkale',
        type: 'child',
        isChecked: false,
        label: 'Kırıkkale',
      },
      {
        value: 'Kırklareli',
        type: 'child',
        isChecked: false,
        label: 'Kırklareli',
      },
      { value: 'Kırşehir', type: 'child', isChecked: false, label: 'Kırşehir' },
      { value: 'Kocaeli', type: 'child', isChecked: false, label: 'Kocaeli' },
      { value: 'Konya', type: 'child', isChecked: false, label: 'Konya' },
      { value: 'Kütahya', type: 'child', isChecked: false, label: 'Kütahya' },
      { value: 'Malatya', type: 'child', isChecked: false, label: 'Malatya' },
      { value: 'Manisa', type: 'child', isChecked: false, label: 'Manisa' },
      { value: 'Mardin', type: 'child', isChecked: false, label: 'Mardin' },
      { value: 'Mersin', type: 'child', isChecked: false, label: 'Mersin' },
      { value: 'Muğla', type: 'child', isChecked: false, label: 'Muğla' },
      { value: 'Muş', type: 'child', isChecked: false, label: 'Muş' },
      { value: 'Nevşehir', type: 'child', isChecked: false, label: 'Nevşehir' },
      { value: 'Niğde', type: 'child', isChecked: false, label: 'Niğde' },
      { value: 'Ordu', type: 'child', isChecked: false, label: 'Ordu' },
      { value: 'Osmaniye', type: 'child', isChecked: false, label: 'Osmaniye' },
      { value: 'Rize', type: 'child', isChecked: false, label: 'Rize' },
      { value: 'Sakarya', type: 'child', isChecked: false, label: 'Sakarya' },
      { value: 'Samsun', type: 'child', isChecked: false, label: 'Samsun' },
      {
        value: 'Şanlıurfa',
        type: 'child',
        isChecked: false,
        label: 'Şanlıurfa',
      },
      { value: 'Siirt', type: 'child', isChecked: false, label: 'Siirt' },
      { value: 'Sinop', type: 'child', isChecked: false, label: 'Sinop' },
      { value: 'Şırnak', type: 'child', isChecked: false, label: 'Şırnak' },
      { value: 'Sivas', type: 'child', isChecked: false, label: 'Sivas' },
      { value: 'Tekirdağ', type: 'child', isChecked: false, label: 'Tekirdağ' },
      { value: 'Tokat', type: 'child', isChecked: false, label: 'Tokat' },
      { value: 'Trabzon', type: 'child', isChecked: false, label: 'Trabzon' },
      { value: 'Tunceli', type: 'child', isChecked: false, label: 'Tunceli' },
      { value: 'Uşak', type: 'child', isChecked: false, label: 'Uşak' },
      { value: 'Van', type: 'child', isChecked: false, label: 'Van' },
      { value: 'Yalova', type: 'child', isChecked: false, label: 'Yalova' },
      { value: 'Yozgat', type: 'child', isChecked: false, label: 'Yozgat' },
      {
        value: 'Zonguldak',
        type: 'child',
        isChecked: false,
        label: 'Zonguldak',
      },
    ],
    label: 'Turkey',
  },

  {
    value: 'Ukraine',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Cherkasy Oblast',
        type: 'child',
        isChecked: false,
        label: 'Cherkasy Oblast',
      },
      {
        value: 'Chernihiv Oblast',
        type: 'child',
        isChecked: false,
        label: 'Chernihiv Oblast',
      },
      {
        value: 'Chernivtsi Oblast',
        type: 'child',
        isChecked: false,
        label: 'Chernivtsi Oblast',
      },
      {
        value: 'Dnipropetrovsk Oblast',
        type: 'child',
        isChecked: false,
        label: 'Dnipropetrovsk Oblast',
      },
      {
        value: 'Donetsk Oblast',
        type: 'child',
        isChecked: false,
        label: 'Donetsk Oblast',
      },
      {
        value: 'Ivano-Frankivsk Oblast',
        type: 'child',
        isChecked: false,
        label: 'Ivano-Frankivsk Oblast',
      },
      {
        value: 'Kharkiv Oblast',
        type: 'child',
        isChecked: false,
        label: 'Kharkiv Oblast',
      },
      {
        value: 'Kherson Oblast',
        type: 'child',
        isChecked: false,
        label: 'Kherson Oblast',
      },
      {
        value: 'Khmelnytskyi Oblast',
        type: 'child',
        isChecked: false,
        label: 'Khmelnytskyi Oblast',
      },
      {
        value: 'Kirovohrad Oblast',
        type: 'child',
        isChecked: false,
        label: 'Kirovohrad Oblast',
      },
      {
        value: 'Kyiv Oblast',
        type: 'child',
        isChecked: false,
        label: 'Kyiv Oblast',
      },
      {
        value: 'Luhansk Oblast',
        type: 'child',
        isChecked: false,
        label: 'Luhansk Oblast',
      },
      {
        value: 'Lviv Oblast',
        type: 'child',
        isChecked: false,
        label: 'Lviv Oblast',
      },
      {
        value: 'Mykolaiv Oblast',
        type: 'child',
        isChecked: false,
        label: 'Mykolaiv Oblast',
      },
      {
        value: 'Odessa Oblast',
        type: 'child',
        isChecked: false,
        label: 'Odessa Oblast',
      },
      {
        value: 'Poltava Oblast',
        type: 'child',
        isChecked: false,
        label: 'Poltava Oblast',
      },
      {
        value: 'Rivne Oblast',
        type: 'child',
        isChecked: false,
        label: 'Rivne Oblast',
      },
      {
        value: 'Sumy Oblast',
        type: 'child',
        isChecked: false,
        label: 'Sumy Oblast',
      },
      {
        value: 'Ternopil Oblast',
        type: 'child',
        isChecked: false,
        label: 'Ternopil Oblast',
      },
      {
        value: 'Vinnytsia Oblast',
        type: 'child',
        isChecked: false,
        label: 'Vinnytsia Oblast',
      },
      {
        value: 'Volyn Oblast',
        type: 'child',
        isChecked: false,
        label: 'Volyn Oblast',
      },
      {
        value: 'Zakarpattia Oblast',
        type: 'child',
        isChecked: false,
        label: 'Zakarpattia Oblast',
      },
      {
        value: 'Zaporizhzhia Oblast',
        type: 'child',
        isChecked: false,
        label: 'Zaporizhzhia Oblast',
      },
      {
        value: 'Zhytomyr Oblast',
        type: 'child',
        isChecked: false,
        label: 'Zhytomyr Oblast',
      },
    ],
    label: 'Ukraine',
  },

  {
    value: 'United Arab Emirates',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Abu Dhabi',
        type: 'child',
        isChecked: false,
        label: 'Abu Dhabi',
      },
      { value: 'Ajman', type: 'child', isChecked: false, label: 'Ajman' },
      { value: 'Dubai', type: 'child', isChecked: false, label: 'Dubai' },
      { value: 'Fujairah', type: 'child', isChecked: false, label: 'Fujairah' },
      {
        value: 'Ras Al Khaimah',
        type: 'child',
        isChecked: false,
        label: 'Ras Al Khaimah',
      },
      { value: 'Sharjah', type: 'child', isChecked: false, label: 'Sharjah' },
      {
        value: 'Umm Al Quwain',
        type: 'child',
        isChecked: false,
        label: 'Umm Al Quwain',
      },
    ],
    label: 'United Arab Emirates',
  },

  {
    value: 'United Kingdom',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      {
        value: 'Bedfordshire',
        type: 'child',
        isChecked: false,
        label: 'Bedfordshire',
      },
      {
        value: 'Berkshire',
        type: 'child',
        isChecked: false,
        label: 'Berkshire',
      },
      { value: 'Bristol', type: 'child', isChecked: false, label: 'Bristol' },
      {
        value: 'Buckinghamshire',
        type: 'child',
        isChecked: false,
        label: 'Buckinghamshire',
      },
      {
        value: 'Cambridgeshire',
        type: 'child',
        isChecked: false,
        label: 'Cambridgeshire',
      },
      { value: 'Cheshire', type: 'child', isChecked: false, label: 'Cheshire' },
      {
        value: 'City of London',
        type: 'child',
        isChecked: false,
        label: 'City of London',
      },
      { value: 'Cornwall', type: 'child', isChecked: false, label: 'Cornwall' },
      {
        value: 'County Durham',
        type: 'child',
        isChecked: false,
        label: 'County Durham',
      },
      { value: 'Cumbria', type: 'child', isChecked: false, label: 'Cumbria' },
      {
        value: 'Derbyshire',
        type: 'child',
        isChecked: false,
        label: 'Derbyshire',
      },
      { value: 'Devon', type: 'child', isChecked: false, label: 'Devon' },
      { value: 'Dorset', type: 'child', isChecked: false, label: 'Dorset' },
      {
        value: 'East Riding of Yorkshire',
        type: 'child',
        isChecked: false,
        label: 'East Riding of Yorkshire',
      },
      {
        value: 'East Sussex',
        type: 'child',
        isChecked: false,
        label: 'East Sussex',
      },
      { value: 'Essex', type: 'child', isChecked: false, label: 'Essex' },
      {
        value: 'Gloucestershire',
        type: 'child',
        isChecked: false,
        label: 'Gloucestershire',
      },
      {
        value: 'Greater London',
        type: 'child',
        isChecked: false,
        label: 'Greater London',
      },
      {
        value: 'Greater Manchester',
        type: 'child',
        isChecked: false,
        label: 'Greater Manchester',
      },
      {
        value: 'Hampshire',
        type: 'child',
        isChecked: false,
        label: 'Hampshire',
      },
      {
        value: 'Herefordshire',
        type: 'child',
        isChecked: false,
        label: 'Herefordshire',
      },
      {
        value: 'Hertfordshire',
        type: 'child',
        isChecked: false,
        label: 'Hertfordshire',
      },
      {
        value: 'Isle of Wight',
        type: 'child',
        isChecked: false,
        label: 'Isle of Wight',
      },
      {
        value: 'Isles of Scilly',
        type: 'child',
        isChecked: false,
        label: 'Isles of Scilly',
      },
      { value: 'Kent', type: 'child', isChecked: false, label: 'Kent' },
      {
        value: 'Lancashire',
        type: 'child',
        isChecked: false,
        label: 'Lancashire',
      },
      {
        value: 'Leicestershire',
        type: 'child',
        isChecked: false,
        label: 'Leicestershire',
      },
      {
        value: 'Lincolnshire',
        type: 'child',
        isChecked: false,
        label: 'Lincolnshire',
      },
      {
        value: 'Merseyside',
        type: 'child',
        isChecked: false,
        label: 'Merseyside',
      },
      { value: 'Norfolk', type: 'child', isChecked: false, label: 'Norfolk' },
      {
        value: 'Northamptonshire',
        type: 'child',
        isChecked: false,
        label: 'Northamptonshire',
      },
      {
        value: 'Northumberland',
        type: 'child',
        isChecked: false,
        label: 'Northumberland',
      },
      {
        value: 'North Yorkshire',
        type: 'child',
        isChecked: false,
        label: 'North Yorkshire',
      },
      {
        value: 'Nottinghamshire',
        type: 'child',
        isChecked: false,
        label: 'Nottinghamshire',
      },
      {
        value: 'Oxfordshire',
        type: 'child',
        isChecked: false,
        label: 'Oxfordshire',
      },
      { value: 'Rutland', type: 'child', isChecked: false, label: 'Rutland' },
      {
        value: 'Shropshire',
        type: 'child',
        isChecked: false,
        label: 'Shropshire',
      },
      { value: 'Somerset', type: 'child', isChecked: false, label: 'Somerset' },
      {
        value: 'South Yorkshire',
        type: 'child',
        isChecked: false,
        label: 'South Yorkshire',
      },
      {
        value: 'Staffordshire',
        type: 'child',
        isChecked: false,
        label: 'Staffordshire',
      },
      { value: 'Suffolk', type: 'child', isChecked: false, label: 'Suffolk' },
      { value: 'Surrey', type: 'child', isChecked: false, label: 'Surrey' },
      {
        value: 'Tyne and Wear',
        type: 'child',
        isChecked: false,
        label: 'Tyne and Wear',
      },
      {
        value: 'Warwickshire',
        type: 'child',
        isChecked: false,
        label: 'Warwickshire',
      },
      {
        value: 'West Midlands',
        type: 'child',
        isChecked: false,
        label: 'West Midlands',
      },
      {
        value: 'West Sussex',
        type: 'child',
        isChecked: false,
        label: 'West Sussex',
      },
      {
        value: 'West Yorkshire',
        type: 'child',
        isChecked: false,
        label: 'West Yorkshire',
      },
      {
        value: 'Wiltshire',
        type: 'child',
        isChecked: false,
        label: 'Wiltshire',
      },
      {
        value: 'Worcestershire',
        type: 'child',
        isChecked: false,
        label: 'Worcestershire',
      },
    ],
    label: 'United Kingdom',
  },

  {
    value: 'United States',
    type: 'parent',
    isChecked: false,
    isOpen: false,
    children: [
      { value: 'Alabama', type: 'child', isChecked: false, label: 'Alabama' },
      { value: 'Alaska', type: 'child', isChecked: false, label: 'Alaska' },
      { value: 'Arizona', type: 'child', isChecked: false, label: 'Arizona' },
      { value: 'Arkansas', type: 'child', isChecked: false, label: 'Arkansas' },
      {
        value: 'California',
        type: 'child',
        isChecked: false,
        label: 'California',
      },
      { value: 'Colorado', type: 'child', isChecked: false, label: 'Colorado' },
      {
        value: 'Connecticut',
        type: 'child',
        isChecked: false,
        label: 'Connecticut',
      },
      { value: 'Delaware', type: 'child', isChecked: false, label: 'Delaware' },
      { value: 'Florida', type: 'child', isChecked: false, label: 'Florida' },
      { value: 'Georgia', type: 'child', isChecked: false, label: 'Georgia' },
      { value: 'Hawaii', type: 'child', isChecked: false, label: 'Hawaii' },
      { value: 'Idaho', type: 'child', isChecked: false, label: 'Idaho' },
      { value: 'Illinois', type: 'child', isChecked: false, label: 'Illinois' },
      { value: 'Indiana', type: 'child', isChecked: false, label: 'Indiana' },
      { value: 'Iowa', type: 'child', isChecked: false, label: 'Iowa' },
      { value: 'Kansas', type: 'child', isChecked: false, label: 'Kansas' },
      { value: 'Kentucky', type: 'child', isChecked: false, label: 'Kentucky' },
      {
        value: 'Louisiana',
        type: 'child',
        isChecked: false,
        label: 'Louisiana',
      },
      { value: 'Maine', type: 'child', isChecked: false, label: 'Maine' },
      { value: 'Maryland', type: 'child', isChecked: false, label: 'Maryland' },
      {
        value: 'Massachusetts',
        type: 'child',
        isChecked: false,
        label: 'Massachusetts',
      },
      { value: 'Michigan', type: 'child', isChecked: false, label: 'Michigan' },
      {
        value: 'Minnesota',
        type: 'child',
        isChecked: false,
        label: 'Minnesota',
      },
      {
        value: 'Mississippi',
        type: 'child',
        isChecked: false,
        label: 'Mississippi',
      },
      { value: 'Missouri', type: 'child', isChecked: false, label: 'Missouri' },
      { value: 'Montana', type: 'child', isChecked: false, label: 'Montana' },
      { value: 'Nebraska', type: 'child', isChecked: false, label: 'Nebraska' },
      { value: 'Nevada', type: 'child', isChecked: false, label: 'Nevada' },
      {
        value: 'New Hampshire',
        type: 'child',
        isChecked: false,
        label: 'New Hampshire',
      },
      {
        value: 'New Jersey',
        type: 'child',
        isChecked: false,
        label: 'New Jersey',
      },
      {
        value: 'New Mexico',
        type: 'child',
        isChecked: false,
        label: 'New Mexico',
      },
      { value: 'New York', type: 'child', isChecked: false, label: 'New York' },
      {
        value: 'North Carolina',
        type: 'child',
        isChecked: false,
        label: 'North Carolina',
      },
      {
        value: 'North Dakota',
        type: 'child',
        isChecked: false,
        label: 'North Dakota',
      },
      { value: 'Ohio', type: 'child', isChecked: false, label: 'Ohio' },
      { value: 'Oklahoma', type: 'child', isChecked: false, label: 'Oklahoma' },
      { value: 'Oregon', type: 'child', isChecked: false, label: 'Oregon' },
      {
        value: 'Pennsylvania',
        type: 'child',
        isChecked: false,
        label: 'Pennsylvania',
      },
      {
        value: 'Rhode Island',
        type: 'child',
        isChecked: false,
        label: 'Rhode Island',
      },
      {
        value: 'South Carolina',
        type: 'child',
        isChecked: false,
        label: 'South Carolina',
      },
      {
        value: 'South Dakota',
        type: 'child',
        isChecked: false,
        label: 'South Dakota',
      },
      {
        value: 'Tennessee',
        type: 'child',
        isChecked: false,
        label: 'Tennessee',
      },
      { value: 'Texas', type: 'child', isChecked: false, label: 'Texas' },
      { value: 'Utah', type: 'child', isChecked: false, label: 'Utah' },
      { value: 'Vermont', type: 'child', isChecked: false, label: 'Vermont' },
      { value: 'Virginia', type: 'child', isChecked: false, label: 'Virginia' },
      {
        value: 'Washington',
        type: 'child',
        isChecked: false,
        label: 'Washington',
      },
      {
        value: 'West Virginia',
        type: 'child',
        isChecked: false,
        label: 'West Virginia',
      },
      {
        value: 'Wisconsin',
        type: 'child',
        isChecked: false,
        label: 'Wisconsin',
      },
      { value: 'Wyoming', type: 'child', isChecked: false, label: 'Wyoming' },
    ],
    label: 'United States',
  },
];
